### ISSUE TITLE
Install Error 167 Trollstore

### ISSUE THREAD

**Issue by HaidarPhantom** [itsnebulalol/deb-to-ipa#2]
i tried a few debs like appsmanager , flex3 etc... 
non of them installed via trollstore and im facing error 167
" The IPA file does not appear to contain an app."

**Comment by itsnebulalol** [comment]
Hi, if you get that error, then the deb probably doesn’t contain an app, or just won’t work. Have you tried CocoaTop? It worked for me.

**Comment by itsnebulalol** [comment]
Never mind, made an error in the workflow. Make sure to merge upstream.

**Comment by HaidarPhantom** [comment]
solved after merge upstream . Thanks
