### ISSUE TITLE
So many repos don’r seems to work

### ISSUE THREAD

**Issue by Alot1z** [itsnebulalol/deb-to-ipa#7]
Hey would just hear if it’s possible to make a fix so this tool works for more repos

**Comment by itsnebulalol** [comment]
What repos don’t work?

**Comment by Alot1z** [comment]
Yea so there's not 
https://www.ios-repo-updates.com/repository/procursus/package/shell-cmds/
https://www.ios-repo-updates.com/repository/chimera-repo/package/shell-cmds/
https://www.ios-repo-updates.com/repository/martin-pham-cydia/package/com.martinpham.swipe2killall/

So these didn't work, i forgot the rest i tried as well

**Comment by itsnebulalol** [comment]
Any error in particular, can you send the workflow runs

**Comment by Alot1z** [comment]
From what i saw as i briefly went though some of them. It's exit code 1 & exit code 2 that's the problem


 cannot stat '/home/runner/work/deb-to-ipa/deb-to-ipa/app/Applications/*': No such file or directory
Error: Process completed with exit code 1.

dpkg-deb: error: '/home/runner/work/deb-to-ipa/deb-to-ipa/app.deb' is not a Debian format archive
Error: Process completed with exit code 2.

**Comment by itsnebulalol** [comment]
> cannot stat '/home/runner/work/deb-to-ipa/deb-to-ipa/app/Applications/*': No such file or directory

It’s either not a direct link to the deb, or the deb doesn’t contain an app.

> dpkg-deb: error: '/home/runner/work/deb-to-ipa/deb-to-ipa/app.deb' is not a Debian format archive

Probably not a direct link to the deb. Can you send the links of the debs?

**Comment by Alot1z** [comment]
alright the first case when the debs are giving off that error, it's probably as you says they don't contain an app

to the second error, 
It link the exect deb link to the file but here you got this is one of them
https://apt.procurs.us/pool/main/iphoneos-arm64/1700/dpkg/dpkg_1.21.9_iphoneos-arm.deb

From this package
https://www.ios-repo-updates.com/repository/procursus/package/dpkg/

**Comment by itsnebulalol** [comment]
dpkg doesn’t contain an app.

**Comment by Alot1z** [comment]
I appreciate the help man, there's not a work around the debs that don't have the app?

for the second error, i just tried converting the Herpy deb, i i assume this it the one you talking about right?
https://www.ios-repo-updates.com/repository/chariz/package/me.midnightchips.harpy-reloaded/

it unfortunately still gives the exit code 2, as you can see in the job-log

Run curl -L -o /home/runner/work/deb-to-ipa/deb-to-ipa/app.deb "https://repo.chariz.com/debs/me.midnightchips.harpy-reloaded_1.0.1_iphoneos-arm.deb"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   [13](https://github.com/Alot1z/deb-to-ipa/actions/runs/3085515759/jobs/4988892106#step:2:14)8  100   138    0     0    770      0 --:--:-- --:--:-- --:--:--   766
100   138  100   138    0     0    770      0 --:--:-- --:--:-- --:--:--   766

100    74    0    74    0     0    [20](https://github.com/Alot1z/deb-to-ipa/actions/runs/3085515759/jobs/4988892106#step:2:21)2      0 --:--:-- --:--:-- --:--:--   202
dpkg-deb: error: '/home/runner/work/deb-to-ipa/deb-to-ipa/app.deb' is not a Debian format archive
Error: Process completed with exit code 2.

**Comment by itsnebulalol** [comment]
It just redirects to the buy page, which isn’t a deb

**Comment by Alot1z** [comment]
I see thanks for the answers
